config/routes.rb
Rails.application.routes.draw do
  resources :coupons

  resources :deals

end

app/models/certificate.rb
class Certificate < Deal
  
  def profit
    cost_without_discount - pay
  end
end

app/models/codepack.rb
class Codepack < ActiveRecord::Base

  has_one :coupon
  belongs_to :deal
  #неиспользованые коды
  scope :not_used, lambda { where("used != ? OR used IS NULL", true) }
  #первый неиспользованый код
  scope :not_used_first, lambda { not_used.limit(1).first }
  
end

app/models/coupon.rb
class Coupon < ActiveRecord::Base
  
  validates :user_id, :codepack_id, presence: true
  validate :deal_actually_by_time_and_clients
  
  belongs_to :codepack
#  delegate :deal, :to => :codepack, :allow_nil => true
  has_one :deal, through: :codepack
  
  #акция для купона состоялась?
  def deal_place?
    self.deal.place
  end
  
  
private
  #проверка валидности акции по времени и кол-ву клиентов
  def deal_actually_by_time_and_clients
    self.deal.actually?
  end
  
end

app/models/deal.rb
class Deal < ActiveRecord::Base
  has_many :codepacks
  has_many :coupons, through: :codepacks
  
  # Актуальные по времени

  scope :actually_by_time, lambda { where("start_date < ? and DATETIME(start_date, '+' || life_time || ' hours') > ?", Time.now, Time.now) }
  scope :for_show, lambda { actually_by_time.where(place: false) }
  
  def profit
    raise 'Abstract method'
  end
  
  # кол-во забронированых кодов(купонов)
  def used_codes
    codepacks.where(used: true).size
  end
  
  #проверка валидности акции по времени
  def actually_by_time?
    (start_date.to_datetime < Time.now) && ((start_date.to_datetime + life_time.hours) > Time.now)
  end
  
  #проверка валидности акции по кол-ву клиентов
  def actually_by_clients?
    max_clients > used_codes
  end
  
  #проверка валидности акции по времени и кол-ву клиентов
  def actually?
    actually_by_time? && actually_by_clients?
  end
  
  # создание купона.
  def get_coupon
    code = codepacks.not_used_first
    unless code.blank? && actually?
      Coupon.create(codepack_id: code.id, user_id: 1)
      code.update_attribute(:used, true)
      self.reload
      self.update_attribute(:place, true) if used_codes == max_clients
    else
      false
    end
  end
  
end

app/models/fixed_cost.rb
class FixedCost < Deal
  def profit
    cost_without_discount - (cost_without_discount * discount_percent/100 + pay)
  end
end

app/models/unlimited_cost.rb
class UnlimitedCost < Deal
  def profit
    'потенциально неограниченна'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/coupons_controller.rb
class CouponsController < ApplicationController
  before_action :set_coupon, only: [:show, :edit, :update, :destroy]

  # GET /coupons
  # GET /coupons.json
  def index
    @coupons = Coupon.all
  end

  # GET /coupons/1
  # GET /coupons/1.json
  def show
  end

  # GET /coupons/new
  def new
    @coupon = Coupon.new
  end

  # GET /coupons/1/edit
  def edit
  end

  # POST /coupons
  # POST /coupons.json
  def create
    @coupon = Coupon.new(coupon_params)

    respond_to do |format|
      if @coupon.save
        format.html { redirect_to @coupon, notice: 'Coupon was successfully created.' }
        format.json { render :show, status: :created, location: @coupon }
      else
        format.html { render :new }
        format.json { render json: @coupon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coupons/1
  # PATCH/PUT /coupons/1.json
  def update
    respond_to do |format|
      if @coupon.update(coupon_params)
        format.html { redirect_to @coupon, notice: 'Coupon was successfully updated.' }
        format.json { render :show, status: :ok, location: @coupon }
      else
        format.html { render :edit }
        format.json { render json: @coupon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coupons/1
  # DELETE /coupons/1.json
  def destroy
    @coupon.destroy
    respond_to do |format|
      format.html { redirect_to coupons_url, notice: 'Coupon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coupon
      @coupon = Coupon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coupon_params
      params.require(:coupon).permit(:user_id, :codepack_id)
    end
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  before_action :set_deal, only: [:show, :edit, :update, :destroy]

  # GET /deals
  # GET /deals.json
  def index
    @deals = Deal.all
  end

  # GET /deals/1
  # GET /deals/1.json
  def show
  end

  # GET /deals/new
  def new
    @deal = Deal.new
  end

  # GET /deals/1/edit
  def edit
  end

  # POST /deals
  # POST /deals.json
  def create
    @deal = Deal.new(deal_params)

    respond_to do |format|
      if @deal.save
        format.html { redirect_to @deal, notice: 'Deal was successfully created.' }
        format.json { render :show, status: :created, location: @deal }
      else
        format.html { render :new }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /deals/1
  # PATCH/PUT /deals/1.json
  def update
    respond_to do |format|
      if @deal.update(deal_params)
        format.html { redirect_to @deal, notice: 'Deal was successfully updated.' }
        format.json { render :show, status: :ok, location: @deal }
      else
        format.html { render :edit }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deals/1
  # DELETE /deals/1.json
  def destroy
    @deal.destroy
    respond_to do |format|
      format.html { redirect_to deals_url, notice: 'Deal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deal
      @deal = Deal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def deal_params
      params.require(:deal).permit(:name, :max_clients, :min_clients, :start_date, :life_time, :actually)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coupons_helper.rb
module CouponsHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/views/coupons/_form.html.haml
= form_for @coupon do |f|
  - if @coupon.errors.any?
    #error_explanation
      %h2= "#{pluralize(@coupon.errors.count, "error")} prohibited this coupon from being saved:"
      %ul
        - @coupon.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :codepack_id
    = f.number_field :codepack_id
  .actions
    = f.submit 'Save'

app/views/coupons/edit.html.haml
%h1 Editing coupon

= render 'form'

= link_to 'Show', @coupon
\|
= link_to 'Back', coupons_path

app/views/coupons/index.html.haml
%h1 Listing coupons

%table
  %thead
    %tr
      %th User
      %th Codepack
      %th
      %th
      %th

  %tbody
    - @coupons.each do |coupon|
      %tr
        %td= coupon.user_id
        %td= coupon.codepack_id
        %td= link_to 'Show', coupon
        %td= link_to 'Edit', edit_coupon_path(coupon)
        %td= link_to 'Destroy', coupon, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Coupon', new_coupon_path

app/views/coupons/new.html.haml
%h1 New coupon

= render 'form'

= link_to 'Back', coupons_path

app/views/coupons/show.html.haml
%p#notice= notice

%p
  %b User:
  = @coupon.user_id
%p
  %b Codepack:
  = @coupon.codepack_id

= link_to 'Edit', edit_coupon_path(@coupon)
\|
= link_to 'Back', coupons_path

app/views/deals/_form.html.haml
= form_for @deal do |f|
  - if @deal.errors.any?
    #error_explanation
      %h2= "#{pluralize(@deal.errors.count, "error")} prohibited this deal from being saved:"
      %ul
        - @deal.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :max_clients
    = f.number_field :max_clients
  .field
    = f.label :min_clients
    = f.number_field :min_clients
  .field
    = f.label :start_date
    = f.datetime_select :start_date
  .field
    = f.label :life_time
    = f.number_field :life_time
  .field
    = f.label :actually
    = f.check_box :actually
  .actions
    = f.submit 'Save'

app/views/deals/edit.html.haml
%h1 Editing deal

= render 'form'

= link_to 'Show', @deal
\|
= link_to 'Back', deals_path

app/views/deals/index.html.haml
%h1 Listing deals

%table
  %thead
    %tr
      %th Name
      %th Max clients
      %th Min clients
      %th Start date
      %th Life time
      %th Actually
      %th
      %th
      %th

  %tbody
    - @deals.each do |deal|
      %tr
        %td= deal.name
        %td= deal.max_clients
        %td= deal.min_clients
        %td= deal.start_date
        %td= deal.life_time
        %td= deal.actually
        %td= link_to 'Show', deal
        %td= link_to 'Edit', edit_deal_path(deal)
        %td= link_to 'Destroy', deal, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Deal', new_deal_path

app/views/deals/new.html.haml
%h1 New deal

= render 'form'

= link_to 'Back', deals_path

app/views/deals/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @deal.name
%p
  %b Max clients:
  = @deal.max_clients
%p
  %b Min clients:
  = @deal.min_clients
%p
  %b Start date:
  = @deal.start_date
%p
  %b Life time:
  = @deal.life_time
%p
  %b Actually:
  = @deal.actually

= link_to 'Edit', edit_deal_path(@deal)
\|
= link_to 'Back', deals_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kupon</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>